### PR TITLE
Add redirects for explorers migration

### PR DESCRIPTION
**Pull request by hexagoncircle**
Adds redirects from [redirect mapping spreadsheet](https://docs.google.com/spreadsheets/d/1T78hQe0JwNcQL4WfjYOfr6AMb9KMT-SsB5poBealP6M/edit#gid=344510717) in https://github.com/netlify/marketing/issues/2291

I'm not sure where the explorer site is hosted. I can only find the internal "netlify-explorers" site when I search in the app.

Screenshot 2023-07-18 at 1 03 28 PM

### CODE REVIEW

**Comment by stephan1echung** [comment]
@hexagoncircle is there a way we can test these redirects before merging? it doesn't look like any deploy preview urls ([https://deploy-preview-529--explorers.netlify.app/](https://explorers.netlify.com/*) are redirecting

**Comment by hexagoncircle** [comment]
Oh nice! I didn't see that the deploy preview built. @stephan1echung—yes, my fault. I included the domain in the redirects when we just want it to be relative paths. I just pushed a change. We should be able to test these redirects once the deploy preview is ready

**Comment by stephan1echung** [comment]
Thanks @hexagoncircle ! It looks like https://deploy-preview-529--explorers.netlify.app/api/get-stage-data returns a 200 status code instead of a 404 status code. will that be handled in a separate PR?

**Comment by hexagoncircle** [comment]
@stephan1echung, ah I didn't realize that needed to be done as well! I've moved the api folder out of the page build so all of those api pages should 404: https://deploy-preview-529--explorers.netlify.app/api/get-stage-data

**Comment by hexagoncircle** [comment]
From the [contributing doc](https://github.com/netlify/explorers/blob/main/CONTRIBUTING.md):
 
> All PRs need to be approved by one of the [CODEOWNERS](https://github.com/netlify/explorers/blob/main/.github/CODEOWNERS)

I think we need @netlify/developer-experience @netlify/department-developer-experience to review and approve this before merging. Neither of those handles seem to link so this codeowners file may be outdated 🤔

**Comment by philhawksworth** [comment]
> From the [contributing doc](https://github.com/netlify/explorers/blob/main/CONTRIBUTING.md):
> 
> > All PRs need to be approved by one of the [CODEOWNERS](https://github.com/netlify/explorers/blob/main/.github/CODEOWNERS)
> 
> I think we need @netlify/developer-experience @netlify/department-developer-experience to review and approve this before merging. Neither of those handles seem to link so this codeowners file may be outdated 🤔
> 
> @philhawksworth, are you able to help us merge this work?

Yes, I'll review. Thanks!

**Review by philhawksworth — APPROVED** [review]
Great!

**Comment by hexagoncircle** [comment]
> Required PR Labels Expected — Waiting for status to be reported

I'm not sure what this task is waiting for. @philhawksworth, do you have admin access to this repo's settings?

**Pull request merged**
