### PR TITLE
fix: (#427): turn margin-top value of profile-page class into padding-top

### LINKED ISSUE #427: profile page footer has a rogue top margin
looks like the footer content is escaping its container

Screen Shot 2020-11-23 at 2 58 07 PM

### PR DESCRIPTION
**Pull request by thsnyzkn**
Closes #427

### CODE REVIEW

**Review by sdras — APPROVED** [review]
Looks great, thanks!

**Comment by thsnyzkn** [comment]
Sorry to bother you, but since I don't have any experience with open source projects, does it mean that my change will be effective on the live version? When I check the main branch I don't see my change and the pull request is still open?
Thanks.

**Comment by lindsaylevine** [comment]
> Sorry to bother you, but since I don't have any experience with open source projects, does it mean that my change will be effective on the live version? When I check the main branch I don't see my change and the pull request is still open?
> Thanks.

@thsnyzkn hey, no worries at all!! the change will be effective once you _merge_ the PR. instead of closing the PR, try to hit the green `Squash and merge` button! closing the PR is effectively like cancelling it; it doesn't go anywhere. to get your work/branch in the `main` branch, we need to merge it :). let us know if you have any other questions!

**Comment by thsnyzkn** [comment]
> > Sorry to bother you, but since I don't have any experience with open source projects, does it mean that my change will be effective on the live version? When I check the main branch I don't see my change and the pull request is still open?
> > Thanks.
> 
> @thsnyzkn hey, no worries at all!! the change will be effective once you _merge_ the PR. instead of closing the PR, try to hit the green `Squash and merge` button! closing the PR is effectively like cancelling it; it doesn't go anywhere. to get your work/branch in the `main` branch, we need to merge it :). let us know if you have any other questions!

Thanks for the reply :), but it is prompted as that pull requests can be merged by people who has the write access. I guess, I don't have it

**Comment by lindsaylevine** [comment]
> > > Sorry to bother you, but since I don't have any experience with open source projects, does it mean that my change will be effective on the live version? When I check the main branch I don't see my change and the pull request is still open?
> > > Thanks.
> > 
> > 
> > @thsnyzkn hey, no worries at all!! the change will be effective once you _merge_ the PR. instead of closing the PR, try to hit the green `Squash and merge` button! closing the PR is effectively like cancelling it; it doesn't go anywhere. to get your work/branch in the `main` branch, we need to merge it :). let us know if you have any other questions!
> 
> Thanks for the reply :), but it is prompted as that pull requests can be merged by people who has the write access. I guess, I don't have it

right of course!!! that makes sense :) i'll merge it for you then :)

**Pull request merged**
